# Generated by Django 6.0.3 on 2026-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_menuitem_low_stock_threshold_menuitem_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_status', 'Order Status Updated'), ('menu_added', 'Menu Item Added'), ('menu_updated', 'Menu Item Updated'), ('menu_deleted', 'Menu Item Deleted'), ('inventory_updated', 'Inventory Updated')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
